# Generated by Django 6.0.4 on 2026-04-21 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2048)),
                ('post_url', models.URLField(blank=True, max_length=2048)),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('share_count', models.BigIntegerField(default=0)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.account')),
            ],
            options={
                'ordering': ['-view_count'],
                'unique_together': {('account', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='PostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='accounts.post')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('post', 'date')},
            },
        ),
    ]
