# Generated by Django 6.0.4 on 2026-04-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post_postsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
