# Generated by Django 6.0.4 on 2026-04-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountsnapshot',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
