# Generated by Django 6.0.4 on 2026-04-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('interval', 'Интервал'), ('times', 'Время')], default='interval', max_length=10)),
                ('interval_hours', models.IntegerField(default=6)),
                ('times', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Расписание обновлений',
            },
        ),
    ]
