# Generated by Django 6.0.4 on 2026-04-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_bigint_post_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='following_count',
        ),
        migrations.RemoveField(
            model_name='accountsnapshot',
            name='following_count',
        ),
        migrations.AlterField(
            model_name='account',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('x', 'X (Twitter)'), ('threads', 'Threads')], max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accountsnapshot',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
