# Generated by Django 6.0.4 on 2026-04-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_following_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('x', 'X (Twitter)'), ('threads', 'Threads'), ('facebook', 'Facebook')], max_length=20),
        ),
    ]
