# Generated by Django 6.0.4 on 2026-05-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_account_profile_unavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_unavailable',
            field=models.BooleanField(default=False, help_text='Последнее обновление: профиль удалён или недоступен на площадке.', verbose_name='Профиль на площадке недоступен'),
        ),
    ]
