# Generated by Django 6.0.5 on 2026-05-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_audience_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='autorefreshpoint',
            new_name='accounts_au_local_d_43bfc3_idx',
            old_name='accounts_aut_local_d_229762_idx',
        ),
    ]
