# Generated by Django 5.2.14 on 2026-06-01 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_post_thumbnail_file_and_missing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeBackendConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_backend', models.CharField(choices=[('playwright', 'Playwright'), ('apify', 'Apify')], default='playwright', max_length=16)),
                ('tiktok_backend', models.CharField(choices=[('playwright', 'Playwright'), ('apify', 'Apify')], default='playwright', max_length=16)),
                ('instagram_backend', models.CharField(choices=[('playwright', 'Playwright'), ('apify', 'Apify')], default='playwright', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Способ сбора данных',
            },
        ),
        migrations.AlterField(
            model_name='refreshscheduleconfig',
            name='auto_refresh_platforms',
            field=models.JSONField(blank=True, default=list, help_text='Пусто — все платформы; иначе только перечисленные id платформ.'),
        ),
        migrations.AlterField(
            model_name='refreshscheduleconfig',
            name='refresh_warm_enabled',
            field=models.BooleanField(default=True, help_text='Прогрев Facebook при refresh_all, bulk и автообновлении.'),
        ),
        migrations.CreateModel(
            name='ApifyRefreshJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=32)),
                ('username_snapshot', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('starting', 'Запуск'), ('running', 'Выполняется'), ('succeeded', 'Успех'), ('failed', 'Ошибка'), ('aborted', 'Отменён')], db_index=True, default='queued', max_length=16)),
                ('apify_run_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('apify_actor_id', models.CharField(blank=True, default='', max_length=255)),
                ('apify_dataset_id', models.CharField(blank=True, default='', max_length=64)),
                ('apify_stages', models.JSONField(blank=True, default=list)),
                ('trigger', models.CharField(choices=[('manual', 'Ручной'), ('refresh_all', 'Сбор всех'), ('bulk', 'Массовый'), ('scheduler', 'Расписание')], default='manual', max_length=32)),
                ('parent_batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('run_detail_extra', models.JSONField(blank=True, default=dict)),
                ('normalized_preview', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apify_refresh_jobs', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Задача Apify refresh',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['account', '-started_at'], name='accounts_ap_account_613fa0_idx'), models.Index(fields=['status'], name='accounts_ap_status_4b3d0d_idx')],
            },
        ),
    ]
