# Generated by Django 5.2.14 on 2026-06-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_refreshscheduleconfig_telegram_chat_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.AddField(
            model_name='refreshscheduleconfig',
            name='auto_refresh_owner_ids',
            field=models.JSONField(blank=True, default=list, help_text='Пусто — все владельцы; иначе id владельцев и/или «none» (без владельца).'),
        ),
        migrations.AlterField(
            model_name='refreshscheduleconfig',
            name='auto_refresh_telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Устаревшее: один chat ID; используйте auto_refresh_telegram_chat_ids.', max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.owner'),
        ),
    ]
