# Generated by Django 5.2.14 on 2026-09-08 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_account_is_banned"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Кусок адреса: /reiz или reiz.example.com. Латиница, цифры и дефис.",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Как показывать в интерфейсе.", max_length=255
                    ),
                ),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Выключенный домен не отдаёт данные и не попадает в сводный эфир.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Домен",
                "verbose_name_plural": "Домены",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="scrapebackendconfig",
            name="facebook_fallback_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Facebook: Playwright→Apify при rate limit, антиботе или недоступном профиле в одном прогоне.",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — запись не распределена и видна во всех доменах.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="accounts.domain",
                verbose_name="Домен",
            ),
        ),
        migrations.AddField(
            model_name="accountgroup",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — запись не распределена и видна во всех доменах.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="groups",
                to="accounts.domain",
                verbose_name="Домен",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — запись не распределена и видна во всех доменах.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="countries",
                to="accounts.domain",
                verbose_name="Домен",
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — запись не распределена и видна во всех доменах.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owners",
                to="accounts.domain",
                verbose_name="Домен",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — запись не распределена и видна во всех доменах.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="accounts.domain",
                verbose_name="Домен",
            ),
        ),
    ]
