# Generated by Django 5.2.14 on 2026-05-11 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVisibilityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_platforms', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Глобальная видимость платформ (subs)',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mirror_dashboard_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('avatar_url', models.URLField(blank=True, max_length=1024)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AudienceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('x', 'X (Twitter)'), ('threads', 'Threads'), ('facebook', 'Facebook'), ('rumble', 'Rumble'), ('reddit', 'Reddit')], db_index=True, max_length=20)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('external_id', models.CharField(blank=True, default='', max_length=160)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=2048)),
                ('bio', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('follower_count', models.BigIntegerField(default=0)),
                ('following_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['username'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'username'), name='subs_audience_member_unique_platform_username')],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mirror_dashboard_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('x', 'X (Twitter)'), ('threads', 'Threads'), ('facebook', 'Facebook'), ('rumble', 'Rumble'), ('reddit', 'Reddit')], max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=1024)),
                ('bio', models.TextField(blank=True)),
                ('follower_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('view_count', models.BigIntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('profile_unavailable', models.BooleanField(default=False)),
                ('audience_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='subscribers.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('username', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='AccountAudienceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_memberships', to='subscribers.account')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='subscribers.audiencemember')),
            ],
            options={
                'ordering': ['-last_synced_at'],
                'unique_together': {('account', 'member')},
            },
        ),
    ]
